openapi: 3.0.1
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
- url: http://localhost:3001/api/v1
paths:
  /user/login:
    post:
      tags:
      - User Module
      summary: Login
      description: API for Login
      requestBody:
        description: Login Payload
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        "200":
          description: Login Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/signup:
    post:
      tags:
      - User Module
      summary: Signup
      description: API for Signup
      requestBody:
        description: Signup Payload
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: Signup Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/profile:
    put:
      tags:
      - User Module
      summary: User Profile API
      description: API for updating a user profile
      requestBody:
        description: Update user profile attributes
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      responses:
        "200":
          description: User profile retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
      x-codegen-request-body-name: body
    post:
      tags:
      - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
  /user/accounts/{account-id}:
    get:
      tags:
      - User Module
      description: API for Accounts
      parameters:
      - name: account-id
        in: path
        description: User account ID to fetch all transactions for this account
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Account transactions information retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "401":
          description: Authentication error! The authentication credentials for the
            requested resource are not valid
          content: {}
        "403":
          description: Forbiden access. The client does not have access rights to
            the content.
          content: {}
        "404":
          description: The server cannot find the requested resource.
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
  /user/transactions/{transaction-id}:
    get:
      tags:
      - User Module
      description: API for Transactions
      parameters:
      - name: transaction-id
        in: path
        description: User account ID to fetch all transactions from
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Account information retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "401":
          description: Authentication error! The authentication credentials for the
            requested resource are not valid
          content: {}
        "403":
          description: Forbiden access. The client does not have access rights to
            the content.
          content: {}
        "404":
          description: The server cannot find the requested resource.
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
    patch:
      tags:
      - User Module
      description: API for Transactions
      parameters:
      - name: transaction-id
        in: path
        description: Transaction ID to fetch single transaction details from
        required: true
        schema:
          type: string
      requestBody:
        description: Update transaction attributes
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
        required: true
      responses:
        "200":
          description: Transaction attributes updated and retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionUpdateApiResponse'
        "400":
          description: Invalid Fields
          content: {}
        "401":
          description: Authentication error! The authentication credentials for the
            requested resource are not valid
          content: {}
        "403":
          description: Forbiden access. The client does not have access rights to
            the content.
          content: {}
        "404":
          description: The server cannot find the requested resource.
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
      - Bearer: []
      x-codegen-request-body-name: body
components:
  schemas:
    Tag:
      type: object
      properties:
        transactionId:
          type: string
        transactionDate:
          type: string
        transactionDesctiption:
          type: string
        transactionAmount:
          type: string
        balance:
          type: integer
      xml:
        name: tag
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
        userName:
          type: string
          description: user public name
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    UserProfile:
      type: object
      properties:
        userName:
          type: string
    AccountApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            accountId:
              type: string
            accountName:
              type: string
            availableBalance:
              type: integer
            transactions:
              type: array
              xml:
                wrapped: true
              items:
                $ref: '#/components/schemas/Tag'
    TransactionApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            transactionId:
              type: string
            accountId:
              type: string
            date:
              type: string
            amount:
              type: number
            description:
              type: string
            category:
              type: string
            details:
              type: string
    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
          description: category
        details:
          type: string
          description: details
    TransactionUpdateApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            category:
              type: string
            details:
              type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
